name: MA_ASAD-Grp3-Project

services:

  # RabbitMQ broker
  broker:
    container_name: broker
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: supersecureadmin
    hostname: "rabbit"
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/

volumes:
  rabbitmq-data:
    driver: local